### PR TITLE
Add input command and changelog

### PR DESCRIPTION
**Pull request by araffin**
- Changed `WalkingRobotIKEnv` to include command as input
- Reduced default max speed in `WalkingRobotIKEnv` (from 15 to 8)
- Added velocity in `WalkingRobotIKEnv` observation
- Added `SE_SERVER_ADDR` env variable

All tasks are tested and working =) (and we can now specified a desired linear/angular speed)

### CODE REVIEW

**Comment by OndrejNepozitek** [comment]
Hello Antonin, thanks for the work you're doing in this repository. We should probably schedule a meeting soon to discuss whether you're interested in this use case and what should our next steps be. We're also prepared to help you with adding additional functionality to the gym or setting up the Space Engineers Windows environment if you're still interested in that. Thanks.

**Comment by araffin** [comment]
>We should probably schedule a meeting soon to discuss whether you're interested in this use case and what should our next steps be. 

we should setup a meeting for sure (I'm interested ;)) but first I would like to test it locally and have a minimal "walking" version.
I'm also working in the rl zoo to have exploration/training done in parallel.

>We're also prepared to help you with adding additional functionality to the gym or setting up the Space Engineers Windows environment if you're still interested in that.

Setting up SE on windows will be my next step (I will try to follow the readme and contact you if I need further help).
Could you send me the Veridream binary on my dlr address?

**Comment by araffin** [comment]
Good news, I got parallel training to work faster than expected: https://github.com/DLR-RM/rl-baselines3-zoo/pull/85
See https://github.com/DLR-RM/rl-baselines3-zoo/blob/feat/parallel-train/utils/callbacks.py#L88

**Comment by araffin** [comment]
@OndrejNepozitek  branch is now ready to be merged, please give it a quick look if you have time ;)

**Pull request merged**
