### PR TITLE
Reward function + Autoformating Walking Robot

### LINKED ISSUE #2: Codestyle?
Hello,

As I will contribute to this repo, I was wondering which codestyle was used and if you would be interested by a a PR that would check it automatically using Github CI + add python linting?

Looking at the code, I assume you are using black?

The PR would re-use what was done for SB3 (https://github.com/DLR-RM/stable-baselines3):
- isort for sorting imports
- black for automatic formatting
- flake8 for linting
- (optionally) pytype for static type checking

### PR DESCRIPTION
**Pull request by araffin**
cf #2 and #3 

closes #2 

Reformat everything using black & isort.

This is the current status of my work (still WIP, I need to convert things to the correct coordinate system).

### CODE REVIEW

**Comment by araffin** [comment]
@OndrejNepozitek I think I'm mostly ready on my side, the only thing I need to fix/update is the coordinate system (cf. my TODOs in the code).

For that I need to know whether we can ask the robot to be spawned at a specific location (will be (0, 0, 0)) with a specific orientation?

I will also add a rate limiter in the code soon (to limit the control frequency).

**Comment by OndrejNepozitek** [comment]
Thanks for your work.

How important is it to spawn the robot at exactly (0,0,0)? Is it possible to just subtract the initial position/orientation and pretend that it was spawned at (0,0,0)? The physics engine is slightly non-deterministic so I cannot make sure that the position is exactly (0,0,0). Also, the game doesn't like when I try to spawn the robot too close to the surface so there must be a slight drop from a height which also adds to the inaccuracies. So in theory I can get close to (0,0,0) but not precisely. Also, I can try to get close to a given orientation but it requires some manual tinkering so I can try to do that if you tell me what the orientation should be.

**Comment by araffin** [comment]
>How important is it to spawn the robot at exactly (0,0,0)? 

Not important, that would just simplify some code but not a problem.
I have some code ready to cope with that (It was used to track the real robot on the treadmill).

>Also, I can try to get close to a given orientation but it requires some manual tinkering so I can try to do that if you tell me what the orientation should be.

no worry, we will just need some debug tomorrow and it should work.

**Comment by OndrejNepozitek** [comment]
Do you want to merge this pull request into the master branch or just keep it in the feature branch for the hackathon?

**Comment by araffin** [comment]
I would like to merge it once we have a working/tested version.
I created a branch "misc/veridream" in the [rl zoo](https://github.com/DLR-RM/rl-baselines3-zoo/tree/misc/veridream), so all we need to do try it is:

```
python train.py --algo tqc --env SpaceEngineers-WalkingRobot-IK-v0 --eval-freq -1
```

**Comment by araffin** [comment]
I also added a fake server (https://github.com/GoodAI/SpaceEngineersGym/blob/feat/reward-fn/tests/test_envs.py) so I can debug locally too ;)

**Comment by araffin** [comment]
I think I have a first (probably) working version.
I did some changes in the relative frame (`world_position` in the code) to make it easier to reason about:
- the x axis will be perpendicular to the initial heading (right vector)
- the y axis will be aligned with the initial heading (forward vector) of the robot
- the z axis will point upward (- gravity vector, up vector)

~EDIT:  only a bug in the reset now~ fixed

**Comment by araffin** [comment]
@OndrejNepozitek may I merge it?

**Comment by OndrejNepozitek** [comment]
Sure, it was on my TODO list for this morning. By the way, the last overnight training session wasn't able to further improve the average reward of the robot.

**Comment by araffin** [comment]
>Sure, it was on my TODO list for this morning. By the way, the last overnight training session wasn't able to further improve the average reward of the robot.

ok, thanks for trying out =). I may have to do additional debug locally then before retrying.

**Comment by araffin** [comment]
>ok, thanks for trying out =). I may have to do additional debug locally then before retrying.

I mostly suspect two things:
- the speed may be still too high
- the reward it is optimizing favor dangerous behavior (I will change that)

Otherwise, it could also be:
- a bug in the coordinate system
- not enough information as input to solve the task

**Pull request merged**
